# Generated by Django 2.2.1 on 2019-05-22 14:03

import auctions.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('initial_price', models.PositiveIntegerField()),
                ('current_price', models.PositiveIntegerField()),
                ('number_of_bits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('days_to_end', models.PositiveIntegerField(default=2)),
                ('step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default=auctions.enums.StatusEnum('Open'), max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_owner', to='accounts.Profile')),
                ('participants', models.ManyToManyField(blank=True, related_name='auction_participants', to='accounts.Profile')),
                ('winer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_winer', to='accounts.Profile')),
            ],
        ),
    ]
