# Generated by Django 2.2.1 on 2019-05-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20190522_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='winer',
            new_name='winner',
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
    ]
