# Generated by Django 2.2.1 on 2019-05-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20190523_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='number_of_bits',
            new_name='number_of_bids',
        ),
    ]
